### ISSUE TITLE
ReferenceError when running Netflix-migrate

### ISSUE THREAD

**Issue by psinke1974** [genderquery/netflix-migrate#7]
evalmachine.<anonymous>:2
if ('serviceWorker' in navigator && navigator.serviceWorker.getRegistrations) {
                       ^

ReferenceError: navigator is not defined
    at evalmachine.<anonymous>:2:24
    at Script.runInContext (vm.js:102:20)
    at Object.runInContext (vm.js:280:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:272:12)
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/cheerio/lib/api/traversing.js:300:18
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:914:11
    at /usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:4901:15
    at baseReduce (/usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/usr/local/lib/node_modules/netflix-migrate/node_modules/lodash/lodash.js:9681:14)
    at initialize.exports.map (/usr/local/lib/node_modules/netflix-migrate/node_modules/cheerio/lib/api/traversing.js:299:23)

I do get a login message (email) from Netflix.. NPM version = 6.1.0

**Comment by CrookedGrandma** [comment]
Getting the exact same thing here

**Comment by genderquery** [comment]
Should be fixed as of version 0.0.7.
